### ISSUE TITLE
Repo files seems wrong?!

### ISSUE THREAD

**Issue by dalisoft** [swimauger/image-classifier#1]
Hi @swimauger 

Can you check please repo from scratch and test repo files are correctly>

Thanks

**Comment by swimauger** [comment]
Hey @dalisoft 
Yeah main file in `package.json` is now `ImageClassifier.js`, I did some big refactoring recently. Some of the files and dependencies were either unnecessary or belonged in its own library. Everything in the documentation should be up to date if you are using version 1.0.2 and up. Were you using this library before the update?

Cause if so, a major change happened in the require statement: 
```JavaScript
const { ImageClassifier } = require('image-classifier');
// TO
const ImageClassifier = require('image-classifier');
```

**Comment by dalisoft** [comment]
Sorry then. I just checked this file https://github.com/swimauger/image-classifier/blob/master/index.js and found broken reference. 
Thanks for reply and understanding. 
Sorry again for confusion
