### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: data is not iterable

### ISSUE THREAD

**Issue by ReplitIsOP** [swimauger/image-classifier#2]
Data is not iterable?

const ImageClassifier = require('image-classifier');
const MyClassifier = new ImageClassifier('./mynewdataset.json', false);

MyClassifier.load().then(async function() {
        await MyClassifier.addExample('Tympole', './tympole.png');
    });

**Comment by ReplitIsOP** [comment]
Fixed! Another error: cannot read property infer of undefined

**Comment by swimauger** [comment]
Hey @ReplitIsOP,

Can you copy the exact error message you received and post it in here?

**Comment by ReplitIsOP** [comment]
> Hey @ReplitIsOP,
> 
> Can you copy the exact error message you received and post it in here?

Tensorset parse function is causing the error.

static parse(data) {
        data = JSON.parse(data);
        const dataset = {};
        for (const example of data) {
            dataset[example.label] = tf.tensor(example.values, example.shape);
        }
        return dataset;
    }
    
The data is not iterable because it's an object.

**Comment by ReplitIsOP** [comment]
Can you fix it?

**Comment by swimauger** [comment]
Yes, I think I see the problem. It appears my logic writes if the dataset file exists it will try to read from it, but if the dataset is empty it will parse to non iterable. Is your mynewdataset.json file empty? Normally, the program will automatically generate a dataset file, but I should also write logic to prevent this from happening.

Working on a fix, should be quick!

**Comment by swimauger** [comment]
Fixed with commit [Ignore invalid dataset json file](https://github.com/swimauger/image-classifier/commit/8eb54b1c875f948698bf53e7aa4c2f61c7da3255).

Upgrade to image-classifier@1.0.4
