### ISSUE TITLE
Most of the images are not working!

### ISSUE THREAD

**Issue by ObliviousDonkey** [swimauger/image-classifier#3]
(node:183) UnhandledPromiseRejectionWarning: Error: Invalid TF_Status: 3
Message: Input to reshape is a tensor with 200704 values, but the requested shape requires a multiple of 150528

Some images work, others don't.

**Comment by swimauger** [comment]
Hi @ObliviousDonkey,

Can you send the full error message?

I would like to see where in ImageClassifier it starts to have an issue.

Thanks

**Comment by ObliviousDonkey** [comment]
Any updates? I tried resizing them but still did't work. Try adding this image as an example. It gives the error.
https://assets.poketwo.net/images/805.png?v=26

**Comment by ReplitIsOP** [comment]
Yes, same problem.

**Comment by swimauger** [comment]
Yeah, I was able to reproduce with the image you provided @ObliviousDonkey.

I imagine I'll have to implement some sort of dynamic tensor reshaping logic, though might be a little beyond my understanding lol, I'll see what I can do.

**Comment by swimauger** [comment]
I believe I found the problem, PNG uses an alpha channel and from the looks of things the mobilenet library isn't shaped for 4D tensors. Thankfully the `decodeImage` function comes with an argument for specifying number of channels.

Fix coming up!
