### ISSUE TITLE
Tensorset.stringify is not a function.

### ISSUE THREAD

**Issue by ObliviousDonkey** [swimauger/image-classifier#4]
(node:287) UnhandledPromiseRejectionWarning: TypeError: Tensorset.stringify is not a function
    at ImageClassifier.save (/home/runner/pclassify/node_modules/image-classifier/ImageClassifier.js:38:42)
    at ImageClassifier.addExample (/home/runner/pclassify/node_modules/image-classifier/ImageClassifier.js:51:43)
.......

**Comment by swimauger** [comment]
Hmmm, that doesn't seem right. Do you have tensorset installed separately because image-classifier hasn't yet been updated for the latest version of tensorset? If so just run `npm un tensorset`.

**Comment by ObliviousDonkey** [comment]
> Hmmm, that doesn't seem right. Do you have tensorset installed separately because image-classifier hasn't yet been updated for the latest version of tensorset? If so just run `npm un tensorset`.

Still same problem! Looks like Tensorset is broken.

**Comment by ObliviousDonkey** [comment]
And there is only 1 version of tensorset.

**Comment by swimauger** [comment]
@ObliviousDonkey oops, my mistake, package.json specifies any version later than 1.0.1 of Tensorset.

Fixed with image-classifier@1.0.8
