### ISSUE TITLE
Problem with installing dependencis

### ISSUE THREAD

**Issue by UrielOfir** [swimauger/image-classifier#7]
this is the error i get: 
This dependency was not found:

* fs/promises in ./node_modules/image-classifier/lib/ImageClassifier.js

To install it, you can run: npm install --save fs/promises

When I do "npm install --save fs/promises"
I get this error: 

The authenticity of host 'github.com (140.82.121.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.

**Comment by swimauger** [comment]
If you update Node to version >=14 you should be good to go 👍
